version: "3.9"
services:
    nginx:
        image: "nginx:1.23.3-alpine"
        container_name: microservices-laravel-rabbit-nginx
        restart: unless-stopped
        working_dir: /app
        links:
            - php-fpm
        volumes:
            - ".:/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8000:80"
        networks: 
            - microservices

    php-fpm:
        build: docker/php-fpm
        working_dir: /app
        restart: unless-stopped
        links:
            - mariadb
        volumes:
            - ".:/app"
            - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
        environment:
            XDEBUG_MODE: "debug"
        networks: 
            - microservices

    mariadb:
        image: "mariadb:10.10.2"
        container_name: microservices-laravel-rabbit-mariadb
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ".:/app"
            - "./mariadb/data:/var/lib/mysql"
            - "./mariadb/logs:/var/log/mysql"
            - "./mariadb/conf:/etc/mysql"
        environment:
            MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
            MARIADB_DATABASE: "${DB_DATABASE}"
            MARIADB_USER: "${DB_USERNAME}"
            MARIADB_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "3308:3306"
        networks: 
            - microservices

    redis:
        image: "redis:7.0.7-alpine"
        container_name: microservices-laravel-rabbit-redis
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
        networks: 
            - microservices
     
    queue:
        image: cylab/laravel-dev
        container_name: microservices-laravel-rabbit-queue
        volumes:
          - .:/var/www/html
        command: ["php", "artisan", "queue:work", "--verbose", "--tries=3", "--timeout=60"]
        restart: unless-stopped
        env_file: .env
        environment:
          WAIT_HOSTS: web:80
            
networks: 
    microservices:
        driver: bridge

volumes:
  composer_cache:   
